[package]
org = "ravindu"
name = "simple_person"
version = "0.1.0"
distribution = "2201.12.0-20250310-080700-94702e9e"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "ollama.np"
version = "0.1.0"
repository="local"

