[package]
org = "ballerinax"
name = "ollama.np"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["natural programming", "ai", "ollama"]
distribution = "2201.12.0-20250310-080700-94702e9e"

[build-options]
observabilityIncluded = true
